---
version: '3.7'
services:

  sidekiq: &darknet_base 
    container_name: ${NAMESPACE}-sidekiq
    build:
      context: .
      dockerfile: Dockerfile
    image: go-darknet:latest
    working_dir: /darknet
    volumes:
    - darknet-data:/darknet/models
    command: /darknet/download_data.sh

  darknet:
    <<: *darknet_base
    container_name: ${NAMESPACE}-api
    ports:
    - "9003:9003"
    restart: unless-stopped
    depends_on:
    - sidekiq
    command: ["/bin/bash"]
    # command: ["darknet-server"]

volumes:
  darknet-data:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/models
